export const PATHS = {
  home: '/',
  women: '/category/women',
  men: '/category/men',
  kids: '/category/kids',
  brands: '/category/brands',
  sport: '/category/sport',
  cart: '/cart',
  contact: '/contact',
  productDetail: '/products/:id',
  login: '/login',
  register: '/register',
  profile: '/profile',
  admin: '/admin',
  adminProducts: '/admin/products',
  adminProductNew: '/admin/products/new',
  adminProductEdit: '/admin/products/:id/edit',
  adminUsers: '/admin/users',
  adminOrders: '/admin/orders',
}
